[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape    = "Block"

[env]
LC_CTYPE = "en_US.UTF-8"

[scrolling]
history    = 5000
multiplier = 3

[terminal.shell]
program = "/usr/local/bin/fish"
args    = ["--login"]

[window]
decorations  = "full"
startup_mode = "Maximized"
opacity      = 0.9

[font]
size = 14.0

[font.normal]
family = "Monaspace Xenon"
style  = "Regular"

[general]
live_config_reload = true

